# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_toolbox' 
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Variables
vars:
    query_tag: develop_dummy_runid
    environment: dev
    default_unknown_timestamp: 1900-01-01 00:00:00 UTC #parse_timestamp("%Y%m%d", '19000101')
    default_max_timestamp: 9999-12-31 00:00:00 UTC #parse_timestamp("%Y%m%d", '99991231')
    default_min_timestamp: parse_timestamp("%Y%m%d", '19000101')
    default_unknown_date: 1900-01-01 00:00:00 UTC #parse_timestamp("%Y%m%d", '19000101')
    default_unknown_varchar: '-'
    default_na_varchar: 'na'
    default_unknown_integer: '-1'


tests:
  dbt_toolbox:
    dim: 
      +severity: warn
    ods:
      +severity: warn


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
    relation: true
    columns: true

  dbt_toolbox:
    ods:
      tags: ods
      database: <NAME_YOUR_DB>
      l1:
        tags: l1
      ln:
        tags: ln

    dim:
      tags: dim
      database: <NAME_YOUR_DB>
